# Generated by Django 5.2.5 on 2025-08-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='El texto del consejo')),
                ('category', models.CharField(choices=[('alimentacion', 'Alimentación'), ('sueño', 'Sueño')], max_length=20)),
            ],
        ),
    ]
